server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:c:\jts\h2\testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true